esphome:
  name: victron-ble

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: "WLANM43CK6"  # înlocuiește cu SSID-ul tău
  password: "17629344072465916405"  # înlocuiește cu parola ta

substitutions:
  smart_solar_mac_address: "c71b9f5211dd"  # adresa ta MAC
  smart_solar_encryption_key: "91bde301f9f80c2445160b13dacd82ff"  # cheia ta de criptare

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

logger:
  level: DEBUG

esp32_ble_tracker:

victron_ble:
  - id: MySmartSolar
    mac_address: ${smart_solar_mac_address}
    bindkey: ${smart_solar_encryption_key}

sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Battery Current"
    type: BATTERY_CURRENT

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Yield Today"
    type: YIELD_TODAY

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "PV Power"
    type: PV_POWER

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Load Current"
    type: LOAD_CURRENT

binary_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT is in Fault state"
    type: DEVICE_STATE_FAULT

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT has Error"
    type: CHARGER_ERROR

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT state"
    type: DEVICE_STATE

  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Error reason"
    type: CHARGER_ERROR
